spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/family_library
    username: cocoa
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  # Temporarily using a fixed strong secret for debugging. 
  # Replace with your own secure key, possibly from an environment variable in production.
  secret: ThisIsMySuperSecureAndLongFixedSecretKeyForTestingPurposes1234567890
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.familylibrary: DEBUG 